site_name: Algoritmos
repo_url: https://github.com/jalmx/algoritmos
site_description: "Documentación de Algoritmos básicos de Mecatrónica 85"
site_author: Alejandro Leyva
site_url: https://www.alejandro-leyva.com/algoritmos/
edit_uri: ""

theme:
  name: material
  locale: es
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      primary: deep orange
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      primary: deep orange
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  language: es
  logo: icons/favicon.png
  favicon: icons/favicon.png
  features:
    - navigation.footer
    - content.code.copy


markdown_extensions:
  - tables
  - attr_list
  - md_in_html
  - footnotes
  - admonition
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji 
      emoji_generator: !!python/name:material.extensions.emoji.to_svg


extra_javascript:
  - javascripts/mathjax.js
  - javascripts/footer.js
  - javascripts/change_height_markmap.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/d3@7/dist/d3.min.js
  - https://unpkg.com/markmap-lib@0.15.3/dist/browser/index.js
  - https://unpkg.com/markmap-view@0.15.3/dist/browser/index.js

extra:
  homepage: https://www.alejandro-leyva.com/algoritmos/
  version: 1.0
  
  copyright: "Alejandro Leyva"

  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jalmx
    - icon: fontawesome/brands/dev
      link: https://www.alejandro-leyva.com
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/mecatronica85/
    - icon: fontawesome/brands/medium
      link: https://medium.com/@xizuth
    - icon: fontawesome/solid/paper-plane
      link: mailto:alejandro.leyva.us@gmail.com

plugins:
  - search:
      lang: es
      indexing: 'full'
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true
      htmlmin_opts:
          remove_comments: true
      cache_safe: true
  - markmap:
      base_path: docs
      encoding: utf-8
      d3_version: "7"
      lib_version: "0.15.3"
      view_version: "0.15.3"